language: csharp
mono: none
dotnet: 2.0.0

install:
 - dotnet restore 

script:
 - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
 - dotnet build
 - dotnet test UnitTestProject1/UnitTestProject1.csproj