language: csharp
mono: none
dotnet: 2.0.0

before_install:
  - # start your web application and listen on `localhost` 
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
 - dotnet restore

script:
 - export APPLITOOLS_API_KEY=`echo 83w3A7NwCwRhYaPza57flqgyS107H109110QOxC769u5HFlHU110`
 - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
 - dotnet build
 - dotnet test UnitTestProject1/UnitTestProject1.csproj